spring.datasource.url=jdbc:postgresql://localhost:5432/productservice
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ativa pretty print para JSON nas respostas
spring.jackson.serialization.indent_output=true

# Bean Validation messages (opcional)
#spring.messages.basename=messages

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# Desabilita o banner (logo) do Spring Boot
spring.main.banner-mode=off

# Reduz o log ao mínimo
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.springframework.test.context=ERROR
logging.level.org.springframework.boot.test=ERROR
